version: '3'

services:
  rust:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: rust
    volumes:
      - ..:/home/ugis/app
    user: ugis
    stdin_open: true
    ports:
      - 3000:3000
